### ISSUE TITLE
can i send input with this library

### ISSUE THREAD

**Issue by IGmatthewbechard2** [Zuzu-Typ/XInput-Python#7]
i need it for a project

**Comment by Zuzu-Typ** [comment]
Hi there,

it is not possible to send XBox-Controller inputs from software, like it is with keyboard or mouse inputs.
You could create a virtual controller, by creating a fake xinput DLL file (like [x360ce](https://github.com/x360ce/x360ce) does).
If you don't necessarily need to send Controller input, you could use [winput](https://github.com/Zuzu-Typ/winput).

Cheers
--Zuzu_Typ--

**Comment by VangaurdGame** [comment]
i wanted to convert mouse and keyboard to controller
